# 1. Compiler Settings
CXX      = g++
CXXFLAGS = -Wall -g -lncurses
# -MMD: Generate dependency files (.d)
# -MP:  Fix errors if a header file is deleted
DEPFLAGS = -MMD -MP

# 2. Directories
SRC_DIR     = src
OBJ_DIR     = obj
BIN_DIR     = bin
INCLUDE_DIR = include

# 3. Include Paths & Flags
# Combine flags: Include dir + Dependency flags
CPPFLAGS = -I$(INCLUDE_DIR) $(DEPFLAGS)

# 4. Files
TARGET  = $(BIN_DIR)/box_program
SOURCES = $(wildcard $(SRC_DIR)/*.cpp)
OBJECTS = $(patsubst $(SRC_DIR)/%.cpp, $(OBJ_DIR)/%.o, $(SOURCES))
# Create a list of .d files (one for every .o file)
DEPS    = $(OBJECTS:.o=.d)

# 5. Main Build Target
$(TARGET): $(OBJECTS)
	@mkdir -p $(BIN_DIR)
	@echo "Linking..."
	$(CXX) $(CXXFLAGS) -o $@ $^
	@echo "Build successful! Executable is at $(TARGET)"

# 6. Compile Source Files
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp
	@mkdir -p $(OBJ_DIR)
	@echo "Compiling $<..."
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $< -o $@

# 7. Include Dependencies
# This line pulls in the .d files generated by the compiler.
# The dash (-) at the start prevents errors if the files don't exist yet.
-include $(DEPS)

# 8. Run Rule
run: $(TARGET)
	@echo "Running program..."
	@./$(TARGET)

# 9. Clean Rule
clean:
	@echo "Cleaning up..."
	rm -rf $(OBJ_DIR) $(BIN_DIR)

.PHONY: clean run
